/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: video.h
  Source: /home/mi/data/code/personal/VideoTransmit/ubuntu/video.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_VIDEO_H
#define DDSC_VIDEO_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct video_OctetSeq
{
  uint32_t _maximum;
  uint32_t _length;
  char *_buffer;
  bool _release;
} video_OctetSeq;

#define video_OctetSeq__alloc() \
((video_OctetSeq*) dds_alloc (sizeof (video_OctetSeq)));

#define video_OctetSeq_allocbuf(l) \
((char *) dds_alloc ((l) * sizeof (char)))
typedef struct video_Frame
{
  int32_t time_id;
  int32_t frame_id;
  char * from;
  video_OctetSeq frame_bytes;
  int32_t rows;
  int32_t cols;
  int32_t channels;
} video_Frame;

extern const dds_topic_descriptor_t video_Frame_desc;

#define video_Frame__alloc() \
((video_Frame*) dds_alloc (sizeof (video_Frame)));

#define video_Frame_free(d,o) \
dds_sample_free ((d), &video_Frame_desc, (o))

typedef enum video_OperationAction
{
  video_FORWARD,
  video_BACK,
  video_TURN_LEFT,
  video_TURN_RIGHT
} video_OperationAction;

#define video_OperationAction__alloc() \
((video_OperationAction*) dds_alloc (sizeof (video_OperationAction)));

typedef struct video_Operation
{
  int32_t operation_id;
  int32_t opera_seq_num;
  video_OperationAction action;
} video_Operation;

extern const dds_topic_descriptor_t video_Operation_desc;

#define video_Operation__alloc() \
((video_Operation*) dds_alloc (sizeof (video_Operation)));

#define video_Operation_free(d,o) \
dds_sample_free ((d), &video_Operation_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VIDEO_H */
